accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

contractor_site_prices/urls.py
from django.urls import path, include
from .views import *

app_name = 'contractor_site_prices'

urlpatterns = [
    
    path('new_csp/', CreateCSP.as_view(), name='create_csp'),
    path('csp_list/', CSPList.as_view(), name='csp_list'),
    path('csp_detail/<int:pk>/', CSPDetail.as_view(), name='csp_detail'),
    
    path('download_single_csv/<int:pk>/', CSPDownloadSingle.as_view(), name='get_single_csv'),
]

csv_orders/urls.py
from django.urls import path, include
from .views import *

app_name = 'csv_orders'

urlpatterns = [
    
    path('update_item/', UpdateCreateCSVOrder.as_view(), name='update_item'),
    path('csv_orders/', CSVOrderDetail.as_view(), name='orders'),
    path('download_order/<str:item_type>', DownloadOrder.as_view(), name='download_order')
]

sor_entry/urls.py
from django.urls import path, include
from .views import *

app_name = 'sor_entry'

urlpatterns = [
    path('new_sor/', CreateSOR.as_view(), name='create_sor'),
    path('sor_list/', SORList.as_view(), name='sor_list'),
    path('sor_detail/<int:pk>/', SORDetail.as_view(), name='sor_detail'),
    
    path('new_uom/', CreateUOM.as_view(), name='create_uom'),
    path('uom_list/', UOMList.as_view(), name='uom_list'),
    
    path('new_trd/', CreateTRD.as_view(), name='create_trd'),
    path('trd_list/', TRDList.as_view(), name='trd_list'),
    
    path('new_loc/', CreateLOC.as_view(), name='create_loc'),
    path('loc_list/', LOCList.as_view(), name='loc_list'),
    
    path('new_pri/', CreatePRI.as_view(), name='create_pri'),
    path('pri_list/', PRIList.as_view(), name='pri_list'),
    
    path('get_single_csv/<int:pk>/', DownloadCSVSingle.as_view(), name='download_single_csv'),
    path('get_csv_date/<str:date_created>', DownloadCSVDate.as_view(), name='download_csv_date'),
]

sor_pricing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

app_name = 'sor_pricing'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sor_entry/', include('sor_entry.urls', namespace='sor_entry')),
    path('pricing_policy/', include('pricing_policy_entry.urls', namespace='pricing_policy_entry')),
    path('contractor_site_prices/', include('contractor_site_prices.urls', namespace='contractor_site_prices')),
    path('csv_orders/', include('csv_orders.urls', namespace='csv_orders'))
]

sor_pricing/views.py
from django.views import generic



# Home page view 
class HomePage(generic.TemplateView):
    
    # Template 
    template_name = 'sor_pricing/home.html'

templates/sor_pricing/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap5 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <!-- Base stylesheets -->
    <link rel="stylesheet" href="{% static 'sor_pricing/css/navbar.css' %}" />

    <!-- External stylesheets -->
    {% block stylesheet %}{% endblock %}

    <!-- Title -->
    <title>ITS |{% block title %}{% endblock %}</title>
  </head>

  <body>
    {% include 'sor_pricing/navbar.html' %}
    
    <br>
    {% block body %}{% endblock %}
    <br>
  </body>



  <script type="text/javascript">
    var user = "{{ request.user }}"
    var user_is_staff = ("{{ request.user.is_staff }}" === 'True')
    var csrftoken = "{{ csrf_token }}"
  </script>

  <script type="text/javascript" src="{% static 'sor_pricing/js/cart.js' %}"></script>
  {% block scripts %}{% endblock %}
</html>

templates/sor_pricing/home.html
{% extends 'sor_pricing/base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Site Pages</h1>
        </div>
    </div>

    <br>

    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'sor_entry:sor_list' %}">SOR List</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all SOR's</p>
            </div>
        </div>
    </div>

    <br>

    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'contractor_site_prices:csp_list' %}">Contractor Site Prices</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all Contractor Site Prices</p>
            </div>
        </div>
    </div>

    <br>

    {% if user.is_staff %}
    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'sor_entry:uom_list' %}">UOM List</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all UOM codes</p>
            </div>
        </div>
    </div>

    <br>
    
    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'sor_entry:trd_list' %}">TRD List</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all TRD codes</p>
            </div>
        </div>
    </div>

    <br>

    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'sor_entry:loc_list' %}">LOC List</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all LOC codes</p>
            </div>
        </div>
    </div>

    <br>

    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'sor_entry:pri_list' %}">PRI List</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">View all PRI codes</p>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/sor_pricing/navbar.html
{% load static %}

<div class="px-3 py-2 bg-dark text-white border-bottom">
    <div class="container">

        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a class="nav-link px-2" href="{% url 'home' %}">ITS</a></li>
                <li><a class="nav-link px-2" href="{% url 'home' %}">HOME</a></li>
            </ul>

            <ul class="nav col-12 col-lg-auto text-end">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'csv_orders:orders' %}">Order</a>
                </li>
    
                <li class="nav-item">
                    <p class="nav-link disabled" id='welcome-link'>Welcome {{user.username}}</p>
                </li>
    
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}" id='logout-link'>Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                </li>
            {% endif %}
            </ul>
        </div>

    </div>
</div>