accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

contractor_site_prices/urls.py
from django.urls import path, include
from .views import *

app_name = 'contractor_site_prices'

urlpatterns = [
    
    path('new_csp/', CreateCSP.as_view(), name='create_csp'),
    path('csp_list/', CSPList.as_view(), name='csp_list'),
    path('csp_detail/<int:pk>/', CSPDetail.as_view(), name='csp_detail'),
    
    path('download_single_csv/<int:pk>/', CSPDownloadSingle.as_view(), name='get_single_csv'),
]

sor_pricing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

app_name = 'sor_pricing'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sor_entry/', include('sor_entry.urls', namespace='sor_entry')),
    path('pricing_policy/', include('pricing_policy_entry.urls', namespace='pricing_policy_entry')),
    path('contractor_site_prices/', include('contractor_site_prices.urls', namespace='contractor_site_prices')),
    path('csv_orders/', include('csv_orders.urls', namespace='csv_orders'))
]

contractor_site_prices/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from sor_entry.models import SOREntry

# Create your models here.

# Policy code
# LPPC_PPP_PPG_CODE
class PolicyCode(models.Model):
    
    lppc_ppp_ppg_code = models.CharField(max_length=10, unique=True, blank=False, null=False, verbose_name="Pricing Policy Group Code")
    
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.lppc_ppp_ppg_code

# Work programme
# LPPC_PPP_WPR_CODE
class WorkProgramme(models.Model):
    
    lppc_ppp_wpr_code = models.CharField(max_length=10, unique=True, blank=False, null=False, verbose_name="Work Programme")
    
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.lppc_ppp_wpr_code
    
# Contractor Site Prices 
class ContractorSitePrice(models.Model):
    
    lcspg_ppp_ppg_code = models.ManyToManyField(PolicyCode, blank=False, verbose_name="Policy Code")
    
    lcspg_ppp_wpr_code = models.ManyToManyField(WorkProgramme, blank=False, verbose_name="Work Programme")
    
    lcspg_ppc_ppp_start_date = models.DateField(default="2016-05-12", verbose_name="Policy Start Date")
    
    lcspg_ppc_cos_code = models.CharField(max_length=15, blank=False, null=False, verbose_name="Contractor Site Code")
    
    cspg_start_date = models.DateField(default="2016-05-12", verbose_name="Contract Start Date")
    
    cspg_end_date = models.DateField(blank=True, null=True, verbose_name="Contract End Date")
    
    lcsp_sor_code = models.ForeignKey(SOREntry, on_delete=models.CASCADE, verbose_name="SOR Code")
    
    lcsp_price = models.DecimalField(max_digits=8, decimal_places=2, null=False, blank=False, verbose_name="Price")
    
    lcsp_preferred_ind = models.CharField(max_length=1, blank=False, null=False, default="N", verbose_name="Preferred Ind")
    
    ##########################
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=False, null=True)
    
    date_created = models.DateTimeField(auto_now_add=True)
    
    def get_value_list_slice(self, start, stop):
        
        # Generate values 
        values = []
        
        # Get field values in proper formats 
        for field in self._meta.get_fields()[start:stop]:
            
            value = getattr(self, field.name)
            
            if value == None:
                values.append("")
            
            # Reformat datefield
            elif isinstance(field, models.DateField):
                values.append( value.strftime("%d-%b-%Y") )
                
            else:
                values.append(value)
        
        return values
    
    # Return a CSV ready table in array form 
    def get_csv_table_list(self):
        
        # Get base template 
        template = self.get_value_list_slice(2, -4)
        
        # Generate each row
        csv_table = []
        for policy in self.lcspg_ppp_ppg_code.all():
            
            for work_programme in self.lcspg_ppp_wpr_code.all():
                
                # Generate the row 
                csv_table.append( [policy.lppc_ppp_ppg_code, work_programme.lppc_ppp_wpr_code] + template )

        return csv_table
    
    # Redirect 
    def get_absolute_url(self):
        return reverse('contractor_site_prices:csp_list')
    
    def __str__(self):
        return "CSP_{}".format(self.id)

contractor_site_prices/forms.py
from django import forms 

from .models import *


# CSP Create/Update Form 
class CSPForm(forms.ModelForm):
    
    class Meta: 
        
        model = ContractorSitePrice
        
        exclude = ['lcspg_ppc_ppp_start_date', 'cspg_end_date', 'lcsp_preferred_ind', 'user']
        
        widgets = {
            'cspg_start_date': forms.DateInput({'type':'date'}),
            'lcspg_ppp_ppg_code': forms.CheckboxSelectMultiple(),
            'lcspg_ppp_wpr_code':forms.CheckboxSelectMultiple(),
        }

contractor_site_prices/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from .forms import *
from .models import *
import csv

# Create your views here.

###################################################
# Contractor Site Prices 
###################################################

# CSP create view 
class CreateCSP(generic.CreateView):
    
    # Model 
    model = ContractorSitePrice
    
    # Template 
    template_name = 'contractor_site_prices/create_update_form.html'
    
    # Form
    form_class = CSPForm 
    
    # Override form valid to add user 
    def form_valid(self, form):
        
        form.instance.user = self.request.user
        
        return super(CreateCSP, self).form_valid(form)
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New CSP"
        context['cancel_redirect'] = ContractorSitePrice.get_absolute_url(ContractorSitePrice)
        return context
    
# CSP List 
class CSPList(generic.ListView):
    
     # Model 
    model = ContractorSitePrice
    
    # Template 
    template_name = 'contractor_site_prices/csp_list.html'
    
# CSP Detail
class CSPDetail(generic.DetailView):
    
    model = ContractorSitePrice
    
    template_name = 'contractor_site_prices/csp_detail.html'
    
    
    
###################################################
# Contractor Site Prices CSV Download 
###################################################

# Get single CSP as a csv 
class CSPDownloadSingle(generic.View):
    
    def get(self, *args, **kwargs):
        
        # Get the object 
        csp = ContractorSitePrice.objects.get(pk=self.kwargs['pk'])
        
        # Create a response 
        response = HttpResponse(
            content_type='text/csv',
            headers={
                'Content-Disposition': 'attachment; filename="CON_SITE_PRICES_{}_1.dat'
            }
        )
        
        # Write the csv file 
        writer = csv.writer(response, quoting=csv.QUOTE_ALL)
        for line in csp.get_csv_table_list():
            line = [ '{}'.format(l) for l in line ]
            row = ",".join(line)
            writer.writerow( line )
            
        return response
    

contractor_site_prices/templates/contractor_site_prices/create_update_form.html
{% extends 'sor_pricing/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>{{ title }}</h3>
            </div>
    
            <div class="card-body">
    
                <form action="" method="POST">
    
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input class="btn btn-primary" type="submit" value='Submit'>
                    <a class="btn btn-danger" href="{{ cancel_redirect }}"">Cancel</a>
                </form>
    
            </div>
    
        </div>

    </div>
{% endblock %}

contractor_site_prices/templates/contractor_site_prices/csp_detail.html
{% extends 'sor_pricing/base.html' %}
{% load static %}
{% load humanize %}

{% block title %} {{ contractorsiteprice }} {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>{{ contractorsiteprice }}</h3>
                <hr>
                <a class="btn btn-primary" href="{% url 'contractor_site_prices:get_single_csv' pk=contractorsiteprice.pk %}">Download CSV</a>
            </div>
    
            <div class="card-body">

                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Policy Code</th>
                            <th>Work Programme</th>
                            <th>Policy Start Date</th>
                            <th>Contractor Site Code</th>
                            <th>Contract Start Date</th>
                            <th>Contract End Date</th>
                            <th>SOR Code</th>
                            <th>Price ($)</th>
                            <th>Preferred Ind</th>
                        </tr>
                    </thead>

                    {% for line in contractorsiteprice.get_csv_table_list %}
                    <tr>
                        {% for entry in line %}
                        <td>{{ entry }}</td>
                        {% endfor %}
                    </tr>
                        
                    {% empty %}
                        <h4>Something has gone wrong</h4>
                    {% endfor %}
                </table>

            </div>
    
        </div>

    </div>
{% endblock %}

contractor_site_prices/templates/contractor_site_prices/csp_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %} Contractor Site Prices {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Contractor Site Prices</h3>
                <hr>
                <a class="btn btn-primary" href="{% url 'contractor_site_prices:create_csp' %}">New CSP</a>
            </div>

            <div class="card-body">
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>Name</th>
                            <th>Contractor</th>
                            <th>Price</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for csp in contractorsiteprice_list %}

                        <tr>
                            <td><a href="{% url 'contractor_site_prices:csp_detail' pk=csp.pk %}">{{ csp }}</a></td>
                            <td>{{ csp.lcspg_ppc_cos_code }}</td>
                            <td>${{ csp.lcsp_price|intcomma }}</td>
                            <td>{{ csp.user.username|upper }}</td>
                            <td>{{ csp.date_created }}</td>
                            <td><button data-id="{{ csp.pk }}" data-action="add" data-type="csp" class="btn btn-primary btn-sm update-csv-queue" href="">Add</button></td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}
                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}