accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

contractor_site_prices/urls.py
from django.urls import path, include
from .views import *

app_name = 'contractor_site_prices'

urlpatterns = [
    
    path('new_csp/', CreateCSP.as_view(), name='create_csp'),
    path('csp_list/', CSPList.as_view(), name='csp_list'),
    path('csp_detail/<int:pk>/', CSPDetail.as_view(), name='csp_detail'),
    
    path('download_single_csv/<int:pk>/', CSPDownloadSingle.as_view(), name='get_single_csv'),
]

csv_orders/urls.py
from django.urls import path, include
from .views import *

app_name = 'csv_orders'

urlpatterns = [
    
    path('update_item/', UpdateCreateCSVOrder.as_view(), name='update_item'),
    path('csv_orders/', CSVOrderDetail.as_view(), name='orders'),
    path('download_order/<str:item_type>', DownloadOrder.as_view(), name='download_order')
]

sor_entry/urls.py
from django.urls import path, include
from .views import *

app_name = 'sor_entry'

urlpatterns = [
    path('new_sor/', CreateSOR.as_view(), name='create_sor'),
    path('sor_list/', SORList.as_view(), name='sor_list'),
    path('sor_detail/<int:pk>/', SORDetail.as_view(), name='sor_detail'),
    
    path('new_uom/', CreateUOM.as_view(), name='create_uom'),
    path('uom_list/', UOMList.as_view(), name='uom_list'),
    
    path('new_trd/', CreateTRD.as_view(), name='create_trd'),
    path('trd_list/', TRDList.as_view(), name='trd_list'),
    
    path('new_loc/', CreateLOC.as_view(), name='create_loc'),
    path('loc_list/', LOCList.as_view(), name='loc_list'),
    
    path('new_pri/', CreatePRI.as_view(), name='create_pri'),
    path('pri_list/', PRIList.as_view(), name='pri_list'),
    
    path('get_single_csv/<int:pk>/', DownloadCSVSingle.as_view(), name='download_single_csv'),
    path('get_csv_date/<str:date_created>', DownloadCSVDate.as_view(), name='download_csv_date'),
]

sor_pricing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

app_name = 'sor_pricing'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sor_entry/', include('sor_entry.urls', namespace='sor_entry')),
    path('pricing_policy/', include('pricing_policy_entry.urls', namespace='pricing_policy_entry')),
    path('contractor_site_prices/', include('contractor_site_prices.urls', namespace='contractor_site_prices')),
    path('csv_orders/', include('csv_orders.urls', namespace='csv_orders'))
]

csv_orders/models.py
from django.db import models
from contractor_site_prices.models import ContractorSitePrice
from django.contrib.auth.models import User
from sor_entry.models import SOREntry

# Create your models here.

# CSV Download Order
class CSVOrder(models.Model):
    
    sor_entries = models.ManyToManyField(SOREntry)
    
    csp_entries = models.ManyToManyField(ContractorSitePrice)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    
    # Add entry 
    def add(self, item):
        
        # Determine type 
        if isinstance(item, SOREntry):
            self.sor_entries.add(item)
        else:
            self.csp_entries.add(item)
            
    # Remove entry 
    def remove(self, item):
        
        # Determine type 
        if isinstance(item, SOREntry):
            self.sor_entries.remove(item)
        else:
            self.csp_entries.remove(item)

csv_orders/views.py
from django.shortcuts import render
from .models import CSVOrder
from django.views import generic
from sor_entry.models import SOREntry
from contractor_site_prices.models import ContractorSitePrice
from django.http import HttpResponse, JsonResponse
import json
import csv

# Create your views here.

# Create an order list of SOR/CSP entries that need to be turned into a CSV
class UpdateCreateCSVOrder(generic.View):
    
    def post(self, *args, **kwargs):
        
        data = json.loads(self.request.body)
        
        # If the request is for a remove all operation
        if data['action'] == 'remove-all':
            return self.process_remove_all(data)
        else:
            return self.process_csp_sor(data)
        
    # Add or remove individual items
    def process_csp_sor(self, data):
        
        print(data)
        
        item_id = data['item_id']
        action = data['action']
        item_type = data['item_type']
        
        # Determine whether it is a csp or sor object 
        user = self.request.user
        if item_type == 'sor':
            item = SOREntry.objects.get(pk=item_id)
        else:
            item = ContractorSitePrice.objects.get(pk=item_id)
        
        # Get or create a download entry
        order, complete = CSVOrder.objects.get_or_create(user=user)
        
        # Add the object or delete based on action 
        if action == "add":
            order.add(item)
        else:
            order.remove(item)
        
        order.save()
        
        # Delete CSVOrder if there are no sor items in it 
        if (order.sor_entries.count() + order.csp_entries.count()) <= 0:
            order.delete()
            
        return JsonResponse({'DATA':data})
    
    # Remove an entire csp/sor list 
    def process_remove_all(self, data):
        
        action = data['action']
        item_type = data['item_type']
        
        # Determine which one to remove 
        order = CSVOrder.objects.get(user=self.request.user)
        if item_type == "sor":
            order.sor_entries.clear()
        else:
            order.csp_entries.clear()
            
        # Delete CSVOrder if there are no sor items in it 
        if (order.sor_entries.count() + order.csp_entries.count()) <= 0:
            order.delete()
            
        return JsonResponse({'DATA':data})
            
            
    

# "Cart" like page for viewing csv orders
class CSVOrderDetail(generic.DetailView):
    
    template_name = 'csv_orders/csv_orders.html'
    
    def get_object(self):
        
        # Get the users order
        try:
            query = CSVOrder.objects.get(user=self.request.user)
        except:
            query = None
            
        return query
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # CSV Order for this user 
        csv_order = self.get_object()
        
        # Add context
        context['title'] = "Order CSV"
        
        if csv_order:
            context['sor_orders'] = csv_order.sor_entries.all()
            context['csp_orders'] = csv_order.csp_entries.all()
            context['order_id'] = csv_order.pk
            
        return context
    
# Download SOR/CSP entries added to the "cart" as a csv/dat SEPARATELY
class DownloadOrder(generic.View):
    
    def get(self, *args, **kwargs):
        
        # Get the users Order
        obj = CSVOrder.objects.get(user=self.request.user)
        
        # Get item type 
        item_type = self.kwargs['item_type']
        query = obj.sor_entries.all() if item_type == "sor" else obj.csp_entries.all()
        
        # Create response 
        filename = "CON_SITE_PRICES" if item_type == "csp" else "SCHEDULE_OF_RATES"
        response = HttpResponse(
            content_type='text/csv',
            headers={
                'Content-Disposition': 'attachment; filename="{}.dat"'.format(filename)
            }
        )
        
        # Write the csv file 
        writer = csv.writer(response, quoting=csv.QUOTE_ALL)
        
        if item_type == 'sor':
            for entry in query:
                writer.writerow( entry.get_field_values_list() )
        
        else:
            for entry in query:
                for line in entry.get_csv_table_list():
                    line = [ '{}'.format(l) for l in line ]
                    writer.writerow( line )
        
        return response

csv_orders/templates/csv_orders/csv_orders.html
{% extends 'sor_pricing/base.html' %}
{% load static %}
{% load humanize %}

{% block title %} {{ title }} {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>SOR Orders</h3>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:sor_list' %}">SOR List</a>
            </div>
    
            <div class="card-body">
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>SOR Code</th>
                            <th>Description</th>
                            <th>Price</th>
                        </tr>
                    </thead>

                    {% for sor in sor_orders %}

                        <tr>
                            <td><a href="{% url 'sor_entry:sor_detail' pk=sor.pk %}">{{ sor.lsor_code }}</a></td>
                            <td>{{ sor.lsor_description }}</td>
                            <td>${{ sor.lsor_price|intcomma }}</td>
                            <td><button data-id="{{ sor.pk }}" data-action="remove" data-type="sor" class="btn btn-danger btn-sm update-csv-queue">Remove</button></td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Orders</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

            <div class="card-footer">

                {% if sor_orders %}
                    <a class="btn btn-primary btn-sm" href="{% url 'csv_orders:download_order' item_type='sor' %}">Download CSV</a>
                    <a data-action="remove-all" data-type="sor" class="btn btn-danger btn-sm clear-btn">Clear</a>
                {% endif %} 
            </div>
    
        </div>

        <hr>

        <div class="card">

            <div class="card-header">
                <h3>CSP Orders</h3>
                <a class="btn btn-primary btn-sm" href="{% url 'contractor_site_prices:csp_list' %}">CSP List</a>
            </div>
    
            <div class="card-body">
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>Name</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for csp in csp_orders %}

                        <tr>
                            <td><a href="{% url 'contractor_site_prices:csp_detail' pk=csp.pk %}">{{ csp }}</a></td>
                            <td>{{ csp.user }}</td>
                            <td>{{ csp.date_created }}</td>
                            <td><button data-id="{{ csp.pk }}" data-action="remove" data-type="csp" class="btn btn-danger btn-sm update-csv-queue">Remove</button></td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Orders</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

            <div class="card-footer">

                {% if csp_orders %}
                    <a class="btn btn-primary btn-sm" href="{% url 'csv_orders:download_order' item_type='csp' %}">Download CSV</a>
                    <a data-action="remove-all" data-type="csp" class="btn btn-danger btn-sm clear-btn">Clear</a>
                {% endif %} 
            </div>
    
        </div>

    </div>
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'sor_pricing/js/clear_cart.js' %}"></script>
{% endblock %}