accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

sor_entry/urls.py
from django.urls import path, include
from .views import *

app_name = 'sor_entry'

urlpatterns = [
    path('new_sor/', CreateSOR.as_view(), name='create_sor'),
    path('sor_list/', SORList.as_view(), name='sor_list'),
    path('sor_detail/<int:pk>/', SORDetail.as_view(), name='sor_detail'),
    
    path('new_uom/', CreateUOM.as_view(), name='create_uom'),
    path('uom_list/', UOMList.as_view(), name='uom_list'),
    
    path('new_trd/', CreateTRD.as_view(), name='create_trd'),
    path('trd_list/', TRDList.as_view(), name='trd_list'),
    
    path('new_loc/', CreateLOC.as_view(), name='create_loc'),
    path('loc_list/', LOCList.as_view(), name='loc_list'),
    
    path('new_pri/', CreatePRI.as_view(), name='create_pri'),
    path('pri_list/', PRIList.as_view(), name='pri_list'),
    
    path('get_single_csv/<int:pk>/', DownloadCSVSingle.as_view(), name='download_single_csv'),
    path('get_csv_date/<str:date_created>', DownloadCSVDate.as_view(), name='download_csv_date'),
]

sor_pricing/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

app_name = 'sor_pricing'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sor_entry/', include('sor_entry.urls', namespace='sor_entry')),
    path('pricing_policy/', include('pricing_policy_entry.urls', namespace='pricing_policy_entry')),
    path('contractor_site_prices/', include('contractor_site_prices.urls', namespace='contractor_site_prices')),
    path('csv_orders/', include('csv_orders.urls', namespace='csv_orders'))
]

sor_entry/forms.py
from django import forms 
from .models import *

# SOR Create/Update form 
class SORForm(forms.ModelForm):
    
    class Meta: 
        
        model = SOREntry
        
        fields = ['lsor_code', 'lsor_description', 'lsor_reorder_period_no', 'lsor_price', 'lsor_pri_code', 'lsor_hrv_trd_code', 'lsor_hrv_uom_code', 'lsor_hrv_loc_code',]
        
# UOM Create/Update form 
class UOMForm(forms.ModelForm):
    
    class Meta: 
        
        model = UOMCode
        
        fields = ['lsor_hrv_uom_code']
        

# TRD Create/Update form 
class TRDForm(forms.ModelForm):
    
    class Meta: 
        
        model = TRDCode
        
        fields = ['lsor_hrv_trd_code']
        
# LOC Create/Update form 
class LOCForm(forms.ModelForm):
    
    class Meta: 
        
        model = LOCCode 
        
        fields = ['lsor_hrv_loc_code']
        
# LOC Create/Update form 
class PRIForm(forms.ModelForm):
    
    class Meta: 
        
        model = PRICode 
        
        fields = ['lsor_pri_code']
        
        

sor_entry/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, JsonResponse
from django.utils import timezone 

from .filters import SORCodeFilter
from .models import *
from .forms import *

import csv
import json

# Create your views here.

###################################################
# SOR Entry
###################################################

# SOR create view 
class CreateSOR(generic.CreateView):
    
    # Model 
    model = SOREntry
    
    # Template 
    template_name = 'sor_entry/create_update_form.html'
    
    # Form
    form_class = SORForm 
    
    # Override form valid to add user 
    def form_valid(self, form):
        
        form.instance.user = self.request.user
        
        return super(CreateSOR, self).form_valid(form)
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New SOR"
        context['cancel_redirect'] = SOREntry.get_absolute_url(SOREntry)
        return context

# SOR detail view 
class SORDetail(generic.DetailView):
    
    model = SOREntry
    
    template_name = 'sor_entry/sor_detail.html'

# SOR list view 
class SORList(generic.ListView):
    
    model = SOREntry
    
    template_name = 'sor_entry/sor_list.html'
    
    # Filtered context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Filter set 
        sor_filter = SORCodeFilter(self.request.GET, queryset=SOREntry.objects.all())
        
        if self.request.GET.get('date_created'):
            sorentry_list = sor_filter.qs
        else:
            sorentry_list = SOREntry.objects.all()
            
        # Query date 
        query_date = self.request.GET.get('date_created') if self.request.GET.get('date_created') else '-1'
        
        # Add context
        context['query_date'] = query_date
        context['sorentry_list'] = sorentry_list 
        context['sor_filter'] = sor_filter
        
        return context
    


###################################################
# LSOR_HRV_UOM_CODE
###################################################

# UOM create view
class CreateUOM(generic.CreateView):
    
    model = UOMCode
    
    template_name = 'sor_entry/create_update_form.html'
    
    form_class = UOMForm
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New UOM Code"
        context['cancel_redirect'] = UOMCode.get_absolute_url(UOMCode)
        return context

# SOR list view 
class UOMList(generic.ListView):
    
    model = UOMCode
    
    template_name = 'sor_entry/uom_list.html'
    


###################################################
# LSOR_HRV_TRD_CODE
###################################################

# TRD create view
class CreateTRD(generic.CreateView):
    
    model = TRDCode
    
    template_name = 'sor_entry/create_update_form.html'
    
    form_class = TRDForm
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New TRD Code"
        context['cancel_redirect'] = TRDCode.get_absolute_url(TRDCode)
        return context

# TRD list view 
class TRDList(generic.ListView):
    
    model = TRDCode
    
    template_name = 'sor_entry/trd_list.html'



###################################################
# LSOR_HRV_LOC_CODE
###################################################

# LOC create view
class CreateLOC(generic.CreateView):
    
    model = LOCCode
    
    template_name = 'sor_entry/create_update_form.html'
    
    form_class = LOCForm
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New LOC Code"
        context['cancel_redirect'] = LOCCode.get_absolute_url(LOCCode)
        return context

# LOC list view 
class LOCList(generic.ListView):
    
    model = LOCCode
    
    template_name = 'sor_entry/loc_list.html'
    


###################################################
# LSOR_PRI_CODE
###################################################

# PRI create view
class CreatePRI(generic.CreateView):
    
    model = LOCCode
    
    template_name = 'sor_entry/create_update_form.html'
    
    form_class = PRIForm
    
    # Extra context data 
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add context
        context['title'] = "New PRI Code"
        context['cancel_redirect'] = PRICode.get_absolute_url(PRICode)
        return context

# LOC list view 
class PRIList(generic.ListView):
    
    model = PRICode
    
    template_name = 'sor_entry/pri_list.html'



###################################################
# CSV Download
###################################################

# Download a CSV file from a single model
class DownloadCSVSingle(generic.View):
    
    def get(self, *args, **kwargs):
        
        # Get the queried object
        obj = SOREntry.objects.get(pk=self.kwargs['pk'])
        
        # Create response 
        response = HttpResponse(
            content_type='text/csv',
            headers={
                'Content-Disposition': 'attachment; filename="{}.DAT"'.format(obj.lsor_code)
            }
        )
        
        # Write the CSV file
        writer = csv.writer(response, quoting=csv.QUOTE_ALL)
        writer.writerow(obj.get_field_values_list())
        
        return response

# Download SOR entries with a specific date as a csv
class DownloadCSVDate(generic.View):
    
    def get(self, *args, **kwargs):
        
        # Query for SOR entries with date_created as a filter
        date_created = self.kwargs['date_created']
        
        if date_created != '-1':
            sor_entries = SOREntry.objects.filter(date_created__date=date_created)
        else:
            sor_entries = SOREntry.objects.all()
        
        # Create response 
        response = HttpResponse(
            content_type='text/csv',
            headers={
                'Content-Disposition': 'attachment; filename="SOR_LIST.DAT"'
            }
        )
        
        # Write the CSV file
        writer = csv.writer(response, quoting=csv.QUOTE_ALL)
        for sor in sor_entries.all():
            writer.writerow(sor.get_field_values_list())
            
        return response

sor_entry/templates/sor_entry/create_update_form.html
{% extends 'sor_pricing/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>{{ title }}</h3>
            </div>
    
            <div class="card-body">
    
                <form action="" method="POST">
    
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input class="btn btn-primary" type="submit" value='Submit'>
                    <a class="btn btn-danger" href={{ cancel_redirect }}>Cancel</a>
                </form>
    
            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/loc_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}

{% block title %} LOC List {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>LOC Codes</h3>
                <br>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:create_loc' %}">New LOC</a>
                <br>
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>LOC Code</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for loc in loccode_list %}

                        <tr>
                            <td>{{ loc.lsor_hrv_loc_code }}</td>
                            <td>{{ loc.user.user_id }}</td>
                            <td>{{ loc.date_created }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/pri_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}

{% block title %} PRI List {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>PRI Codes</h3>
                <br>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:create_pri' %}">New PRI</a>
                <br>
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>PRI Code</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for pri in pricode_list %}

                        <tr>
                            <td>{{ pri.lsor_pri_code }}</td>
                            <td>{{ pri.user.user_id }}</td>
                            <td>{{ pri.date_created }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/sor_detail.html
{% extends 'sor_pricing/base.html' %}
{% load static %}
{% load humanize %}

{% block title %} {{ sorentry.sor_code }} {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>{{ sorentry.lsor_code }}</h3>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:download_single_csv' pk=sorentry.pk %}">Download as CSV</a>
                <br>
            </div>
    
            <div class="card-body">

                <table class="table table-striped">

                    {% for value in sorentry.get_key_val_tuple %}

                        <tr>
                            <td>{{ value.0|upper }}</td>
                            <td>{{ value.1 }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}
                    
                </table>

            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/sor_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %} SOR List {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>SOR List</h3>
                <hr>
                <h3>Filter Query</h3>

                <form action="">
                    {% csrf_token %}
                    {{ sor_filter.form|crispy }}
                    <br>
                    <input class="btn btn-primary btn-sm" type="submit" value="Submit">
                </form>
                <hr>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:create_sor' %}">New SOR</a>

                {% if sorentry_list %}
                    <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:download_csv_date' date_created=query_date %}">Download CSV</a>
                {% endif %}
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>SOR Code</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for sor in sorentry_list %}

                        <tr>
                            <td><a href="{% url 'sor_entry:sor_detail' pk=sor.pk %}">{{ sor.lsor_code }}</a></td>
                            <td>{{ sor.lsor_description }}</td>
                            <td>${{ sor.lsor_price|intcomma }}</td>
                            <td>{{ sor.user.username|upper }}</td>
                            <td>{{ sor.date_created }}</td>
                            <td><button data-id="{{ sor.pk }}" data-action="add" data-type="sor" class="btn btn-primary btn-sm update-csv-queue" href="">Add</button></td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/trd_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}

{% block title %} LOC List {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>TRD Codes</h3>
                <br>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:create_trd' %}">New TRD</a>
                <br>
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>TRD Code</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for trd in trdcode_list %}

                        <tr>
                            <td>{{ trd.lsor_hrv_trd_code }}</td>
                            <td>{{ trd.user.user_id }}</td>
                            <td>{{ trd.date_created }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}

sor_entry/templates/sor_entry/uom_list.html
{% extends 'sor_pricing/base.html' %}
{% load static %}

{% block title %} UOM List {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>UOM Codes</h3>
                <br>
                <a class="btn btn-primary btn-sm" href="{% url 'sor_entry:create_uom' %}">New UOM</a>
                <br>
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>UOM Code</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                        </tr>
                    </thead>

                    {% for uom in uomcode_list %}

                        <tr>
                            <td>{{ uom.lsor_hrv_uom_code }}</td>
                            <td>{{ uom.user.user_id }}</td>
                            <td>{{ uom.date_created }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Entries</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}